# -*- coding: utf-8 -*-
"""OCR Language Translation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UIAbbcgHuN8FAzMjf036ANJQSSfg8fkW

![Link](https://drive.google.com/uc?id=1ulYLIj5XhDhuFjtRpqhJklxQu-j4NYqL)
"""

!pip install easyocr

!pip3 install googletrans==3.1.0a0

!pip install gTTS

!wget https://i.stack.imgur.com/mk1jX.jpg

from googletrans import Translator
import easyocr
from gtts import gTTS
from IPython.display import Audio

reader = easyocr.Reader(['ta'])
translator = Translator()

import PIL
from PIL import ImageDraw
im = PIL.Image.open("/content/mk1jX.jpg")
im

bounds = reader.readtext('/content/mk1jX.jpg', add_margin=0.55, width_ths=0.7, link_threshold=0.8, decoder='beamsearch',blocklist='=-')
bounds

def draw_boxes(image, bounds, color='yellow', width=2):
    draw = ImageDraw.Draw(image)
    for bound in bounds:
        p0, p1, p2, p3 = bound[0]
        draw.line([*p0, *p1, *p2, *p3, *p0], fill=color, width=width)
    return image

draw_boxes(im, bounds)

text_list = reader.readtext('/content/mk1jX.jpg', add_margin=0.55, width_ths=0.7, link_threshold=0.8, decoder='beamsearch',blocklist='=-', detail=0)
text_list

text_comb=' '.join(text_list)
text_comb

print(translator.detect(text_comb))

text_en=translator.translate(text_comb, src='ta')
print(text_en.text)

ta_tts=gTTS(text_en.text)
ta_tts.save('trans.mp3')

Audio('trans.mp3' , autoplay=True)

ta_tts=gTTS(text_en.text, lang='ja')
ta_tts.save('trans.mp3')

Audio('trans.mp3' , autoplay=True)

text_hi=translator.translate(text_comb, src='ta',dest='hi')
print(text_hi.text)

ta_tts_hi=gTTS(text_hi.text, lang='hi')
ta_tts_hi.save('trans_hi.mp3')

Audio('trans_hi.mp3' , autoplay=True)

text_fr=translator.translate(text_comb, src='ta',dest='fr')
print(text_fr.text)

ta_tts_fr=gTTS(text_fr.text, lang='fr')
ta_tts_fr.save('trans_fr.mp3')

Audio('trans_fr.mp3' , autoplay=True)

